from django.urls import path
from . import views



urlpatterns = [
    path('', views.EventsListView.as_view(), name='dashboard'),
    path('ajax-search/', views.ajax_search, name='ajax_search'),
    path('notifications/', views.notifications, name='notifications'),
    path('mark-notification-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('mark-all-notifications-as-read/', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('create_client/', views.create_client, name='create_client'),
    path('events_list/', views.EventsListView.as_view(), name='events_list'),
    path('get_locations/', views.GetLocationsView.as_view(), name='get_locations'),
    path('get_properties/', views.GetProperties.as_view(), name='get_properties'),
    path('get_event_types/', views.GetEventTypes.as_view(), name='get_event_types'),
    path('get_clients/', views.GetClients.as_view(), name='get_clients'),
    path('get_events/', views.get_events, name='get_events'),
    path('add_property/', views.add_property, name='add_property'),
    path('add_rental_property/', views.add_rental_property, name='add_rental_property'),
    path('events/add/', views.add_event, name='add_event'),
    path('events/edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('events/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('events/toggle_complete/<int:event_id>/', views.toggle_complete, name='toggle_complete'),
    path('events/add_event_type/', views.add_event_type, name='add_event_type'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/<int:client_id>/', views.client_events, name='client_events'),
    path('clients/edit/<int:client_id>/', views.edit_client, name='edit_client'),
    path('clients/delete/<int:client_id>/', views.delete_client, name='delete_client'),
    path('clients/add_notes/<int:client_id>/', views.add_client_notes, name='add_client_notes'),
    path('clients/update_suggestion/', views.suggest_property, name='update_suggestion'),
    path('events/delete_notes/<int:note_id>/<int:client_id>/', views.delete_client_note, name='delete_notes'),
    path('properties/', views.properties_list, name='properties_list'),
    path('properties/<int:property_id>/', views.property_events, name='property_events'),
    path('properties/edit/<int:property_id>/', views.edit_property, name='edit_property'),
    path('properties/delete/<int:property_id>/', views.delete_property, name='delete_property'),
    path('search/', views.search_page, name='search_page'),
    path('google-maps-script/', views.google_maps_proxy, name='google_maps_proxy'),
    path('delete_image/<int:photo_id>/', views.delete_image, name='delete_image'),
    path('settings/',views.settings, name='settings'),
    path('settings/google-authenticate/', views.google_authenticate, name='google_authenticate'),
    path('settings/google-authenticate-callback/', views.google_authenticate_callback, name='google_authenticate_callback'),
    path('settings/import-google-contacts/', views.import_google_contacts, name='import_google_contacts'),
    path('settings/event_types_list/', views.event_types_list, name='event_types_list'),
    path('settings/edit_event_type/<int:event_type_id>/', views.edit_event_type, name='edit_event_type'),
    path('settings/delete_event_type/<int:event_type_id>/', views.delete_event_type, name='delete_event_type'),

    path('settings/client_status_list/', views.client_status_list, name='client_status_list'),
    path('settings/edit_client_status/<int:client_status_id>/', views.edit_client_status, name='edit_client_status'),
    path('settings/add_client_status/', views.add_client_status, name='add_client_status'),
    path('settings/delete_client_status/<int:client_status_id>/', views.delete_client_status, name='delete_client_status'),
    
    path('settings/property_status_list/', views.property_status_list, name='property_status_list'),
    path('settings/edit_property_status/<int:property_status_id>/', views.edit_property_status, name='edit_property_status'),
    path('settings/add_property_status/', views.add_property_status, name='add_property_status'),
    path('settings/delete_property_status/<int:property_status_id>/', views.delete_property_status, name='delete_property_status'),
    
    path('settings/property_type_list/', views.property_type_list, name='property_type_list'),
    path('settings/edit_property_type/<int:property_type_id>/', views.edit_property_type, name='edit_property_type'),
    path('settings/add_property_type/', views.add_property_type, name='add_property_type'),
    path('settings/delete_property_type/<int:property_type_id>/', views.delete_property_type, name='delete_property_type'),
    
    path('settings/property_deal_type_list/', views.property_deal_type_list, name='property_deal_type_list'),
    path('settings/edit_property_deal_type/<int:property_deal_type_id>/', views.edit_property_deal_type, name='edit_property_deal_type'),
    path('settings/add_property_deal_type/', views.add_property_deal_type, name='add_property_deal_type'),
    path('settings/delete_property_deal_type/<int:property_deal_type_id>/', views.delete_property_deal_type, name='delete_property_deal_type'),
    
    path('settings/suggestions_link_settings/', views.suggestions_link_settings, name='suggestions_link_settings'),
]