# Generated by Django 5.0 on 2024-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_facebook_url_customuser_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
