# Generated by Django 5.0 on 2024-02-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_paid_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_paid',
            field=models.BooleanField(default=False),
        ),
    ]
