# Generated by Django 5.0 on 2024-02-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_is_paid_customuser_is_active_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active_paid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_status',
        ),
    ]
