# Generated by Django 5.0 on 2024-01-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_initial'),
        ('Realtor', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinterest',
            old_name='floor_preference',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='clientinterest',
            old_name='rooms',
            new_name='max_floor_preference',
        ),
        migrations.RenameField(
            model_name='clientinterest',
            old_name='price_range',
            new_name='max_price_range',
        ),
        migrations.RenameField(
            model_name='clientinterest',
            old_name='square_meter',
            new_name='max_square_meter',
        ),
        migrations.AddField(
            model_name='clientinterest',
            name='min_floor_preference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinterest',
            name='min_price_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientinterest',
            name='min_square_meter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinterest',
            name='toilets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinterest',
            name='totalrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientinterest',
            name='payment_term',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('loan', 'Loan'), ('leasing', 'Leasing'), ('all', 'All')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Auto_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_auto_suggestions', to='CRM.clent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_auto_suggestions', to='Realtor.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
