# Generated by Django 5.0 on 2024-01-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_rename_floor_preference_clientinterest_bedrooms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto_suggestion',
        ),
    ]
