# Generated by Django 5.0 on 2024-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_remove_clent_is_searching_clent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clent',
            name='status',
            field=models.CharField(choices=[('looking_for_property', 'Looking For Property'), ('looking_for_rental_property', 'Looking For Rental'), ('selling_property', 'Selling property'), ('renting_Property', 'Renting Property'), ('inactive', 'Inactive')], max_length=50, null=True),
        ),
    ]
