# Generated by Django 5.0 on 2024-01-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_clent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clent',
            name='status',
            field=models.CharField(choices=[('looking_for_property', 'Looking For Property'), ('looking_for_rental_property', 'Looking For Rental'), ('selling_property', 'Selling property'), ('renting_Property', 'Renting Property'), ('tenant', 'Tenant'), ('inactive', 'Inactive')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField()),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('clent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clent')),
            ],
        ),
    ]
