# Generated by Django 5.0 on 2024-01-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_rename_clent_statuschangelog_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clent',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clent',
            name='home_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clent',
            name='wedding_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='client_relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('relationship_type', models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clent')),
            ],
        ),
        migrations.CreateModel(
            name='client_social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instgaram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('reddit', 'Reddit')], max_length=255)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clent')),
            ],
        ),
    ]
