# Generated by Django 5.0 on 2024-01-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_clent_birthday_clent_home_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clent',
            name='status',
            field=models.CharField(blank=True, choices=[('looking_for_property', 'Looking For Property'), ('looking_for_rental_property', 'Looking For Rental'), ('selling_property', 'Selling property'), ('renting_Property', 'Renting Property'), ('tenant', 'Tenant'), ('inactive', 'Inactive')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='client_phone_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('other', 'Other')], max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.clent')),
            ],
        ),
    ]
