# Generated by Django 5.0 on 2024-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_alter_clent_status_client_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_social_links',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instgaram'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=255),
        ),
    ]
