# Generated by Django 5.0 on 2024-01-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_clent_facebook_url_clent_instagram_url_and_more'),
        ('Realtor', '0009_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_bought', to='CRM.clent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_owned', to='CRM.clent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='Realtor.property'),
        ),
    ]
