# Generated by Django 5.0 on 2024-01-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_alter_event_event_description_alter_event_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_ampm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_hour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_minute',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
