# Generated by Django 5.0 on 2024-01-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_remove_event_event_time_event_event_ampm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_ampm',
            field=models.CharField(blank=True, choices=[('am', 'AM'), ('am', 'PM')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_hour',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_minute',
            field=models.CharField(blank=True, choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], max_length=5, null=True),
        ),
    ]
