# Generated by Django 5.0 on 2024-01-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_event_is_completed_alter_event_event_ampm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='index_field',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
