# Generated by Django 5.0 on 2024-01-24 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_alter_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_type',
            new_name='event_type_model',
        ),
    ]
