# Generated by Django 5.0 on 2024-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_rename_event_type_event_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_buyer_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_owner_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_property_address',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
