# Generated by Django 5.0 on 2024-01-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_clent_google_resource_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinterest',
            name='additional_feature',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='max_floor_preference',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='max_price_range',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='max_square_meter',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='min_floor_preference',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='min_price_range',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='min_square_meter',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='toilets',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='totalrooms',
        ),
        migrations.RemoveField(
            model_name='clientinterest',
            name='view_sight',
        ),
        migrations.AddField(
            model_name='clientinterest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
