# Generated by Django 5.0 on 2024-01-31 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0025_suggestion_link_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ids', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestion_link_settings',
            name='id',
        ),
        migrations.AlterField(
            model_name='clent',
            name='status',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.client_status_types'),
        ),
        migrations.AlterField(
            model_name='suggestion_link_settings',
            name='contacts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion_link_settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion_link_settings',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
