# Generated by Django 5.0 on 2024-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0027_alter_clent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clent',
            name='status',
            field=models.CharField(blank=True, choices=[('looking_for_property', 'Looking for Property')], max_length=255, null=True),
        ),
    ]
