# Generated by Django 5.0 on 2024-01-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0031_notification_delete_search'),
        ('Realtor', '0009_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.clent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Realtor.property'),
        ),
    ]
