# Generated by Django 5.0 on 2024-01-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0032_notification_client_notification_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
