# Generated by Django 5.0 on 2024-02-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0034_event_participant_property_images'),
        ('Realtor', '0009_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_property', to='Realtor.property'),
        ),
    ]
