# Generated by Django 5.0 on 2024-02-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0037_property_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='property_status',
        ),
    ]
