# Generated by Django 5.0 on 2024-02-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0038_delete_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinterest',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
