# Generated by Django 5.0 on 2024-02-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0040_alter_clientinterest_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clent',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
