# Generated by Django 5.0 on 2024-01-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('office', 'Office'), ('apartment', 'Apartment'), ('house', 'House')], max_length=20)),
                ('deal_type', models.CharField(choices=[('rental', 'Rental'), ('selling', 'Selling')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('sqr_meter', models.IntegerField()),
                ('price_sqrm', models.FloatField(null=True)),
                ('price_month', models.FloatField(null=True)),
                ('condition', models.CharField(choices=[('cash', 'Бэлэн'), ('barter', 'Бартер'), ('Leasing', 'Лизинг'), ('3 plus 1', '3 + 1'), ('6 plus 1', '6 + 1'), ('12 plus 1', '12 + 1'), ('1 plus 1', '1 + 1')], max_length=20)),
                ('description', models.TextField()),
                ('address_lower', models.CharField(editable=False, max_length=255)),
                ('total_floor', models.IntegerField()),
                ('which_floor', models.IntegerField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
