# Generated by Django 5.0 on 2024-01-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(max_length=20),
        ),
    ]
