# Generated by Django 5.0 on 2024-01-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0005_property_design_description_property_dining_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_district_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
