# Generated by Django 5.0 on 2024-01-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0006_property_city_property_country_property_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='sub_district_2',
        ),
    ]
