# Generated by Django 5.0 on 2024-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0007_remove_property_sub_district_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
