# Generated by Django 5.0 on 2024-02-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0009_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
