# Generated by Django 5.0 on 2024-02-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0010_property_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
