# Generated by Django 5.0 on 2024-02-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0011_property_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
