# Generated by Django 5.0 on 2024-02-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0014_property_status_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='Realtor.property_status'),
        ),
    ]
