# Generated by Django 5.0 on 2024-02-13 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0015_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_status_type', to='Realtor.property_status'),
        ),
        migrations.AlterField(
            model_name='property_status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_property_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
