# Generated by Django 5.0 on 2024-02-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0017_deal_type_alter_property_deal_type_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_month',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_types', to='Realtor.property_type'),
        ),
    ]
