# Generated by Django 5.0 on 2024-02-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0018_alter_property_price_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
