# Generated by Django 5.0 on 2024-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtor', '0019_property_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
